#!/usr/bin/env node
// Embeds models/lr_lite_export.json into src/model-data.ts at build time.
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const dir = dirname(fileURLToPath(import.meta.url));
const json = readFileSync(resolve(dir, "../../../models/lr_lite_export.json"), "utf-8");
writeFileSync(
  resolve(dir, "../src/model-data.ts"),
  `// Auto-generated by scripts/embed-model.js — do not edit.\n/* eslint-disable */\nimport type { ModelData } from "./types.js";\nexport const MODEL_DATA: ModelData = ${json};\n`
);
console.log("  model-data.ts generated");